version: '2'
services:
    portfolio-app:
        image: portfolio
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://portfolio-mysql:3306/portfolio?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=portfolio-elasticsearch:9300
        ports:
            - 8080:8080
    portfolio-mysql:
        extends:
            file: mysql.yml
            service: portfolio-mysql
    portfolio-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: portfolio-elasticsearch
